# Generated by Django 5.2.7 on 2025-10-26 13:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('published_at', models.DateField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('categories', models.ManyToManyField(related_name='case_studies', to='knowledgehub.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='case_studies', to='knowledgehub.tag')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='cs_sv_idx'), django.contrib.postgres.indexes.GinIndex(fields=['title', 'abstract'], name='cs_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('categories', models.ManyToManyField(related_name='books', to='knowledgehub.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='books', to='knowledgehub.tag')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='book_sv_idx'), django.contrib.postgres.indexes.GinIndex(fields=['title', 'author', 'description'], name='book_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('categories', models.ManyToManyField(related_name='articles', to='knowledgehub.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='knowledgehub.tag')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='article_search_vector_idx'), django.contrib.postgres.indexes.GinIndex(fields=['title', 'content'], name='article_title_content_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('categories', models.ManyToManyField(related_name='videos', to='knowledgehub.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='knowledgehub.tag')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vid_sv_idx'), django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='vid_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
    ]
